### ISSUE TITLE
CSS3 Nesting

### ISSUE THREAD

**Issue by Gabilabrebi** [SubC4i/Sublime-MavensMate-Monokai#4]
Hello

CSS3 Nesting with and without & is slowly becoming a standard now. It would be really great is the theme could support it.

For example : 
![image](https://github.com/SubC4i/Sublime-MavensMate-Monokai/assets/39853761/963ee019-7b04-4ffa-b762-af77679df69d)

"ol" should be in red here :)

Thank you again for this great theme!

**Comment by SubC4i** [comment]
I believe I found the scope to change the color for that syntax.  Here's a screenshot from my testing.  I will update the extension with the new version soon.
![image](https://github.com/SubC4i/Sublime-MavensMate-Monokai/assets/32463601/c1d4dd9b-b62b-43f6-a8d6-2b45b840d293)

**Comment by Gabilabrebi** [comment]
Thanks! Really appreciated ;)

**Comment by SubC4i** [comment]
New version is now live.

**Comment by Gabilabrebi** [comment]
![image](https://github.com/SubC4i/Sublime-MavensMate-Monokai/assets/39853761/2512c874-0ebd-4af3-942a-c3865fc250d0)

Looks like it breaks recognition after tho :(

**Comment by SubC4i** [comment]
Hmm, I'm not sure if that was occurring before the latest update.  i.e. The lines not highlighting correctly that come after the ol tag.  The change I made was only to make meta.property-name.css appear as the red color.

Upon inspecting the tokens/scopes, I see that the CSS syntax is recognizing the same tokens as different types for some reason.  That's something I cannot control and it will take more consideration if any changes can be made since I don't want to ruin the colors for other types as a result.  For example, min-height after the ol tag is being no longer identified as support.type.property-name.css (which is the normal type).  After the ol tag, it is no longer seen as that.

Was the syntax highlighting colors working as expected before the update for syntaxes that are placed after the ol tag?

**Comment by SubC4i** [comment]
Actually, just reverted back to earlier version of the theme extension and this was happening before the latest update.  i.e. This is a separate issue.  Will let you know if I'm able to fix this behavior since I would need to work around the behavior of the CSS syntax itself.

**Comment by Gabilabrebi** [comment]
Hey, any update on this? Did you find a solution?

**Comment by SubC4i** [comment]
Unfortunately, I’ve haven’t been able to find a solution yet. Also, I haven’t had enough free time to do a deep dive.
